export { itemsSlider } from './consts'
export { footerMenuItems } from './consts'
export { headerMenuItems } from './consts'
export { skillsData } from './consts'
export { tabsItems } from './consts'
export { worksData } from './consts'
export type { TabsStatusType } from './types'
export type { TabsItemsType } from './types'
export type { WorksDataType } from './types'
export type { SkillsDataType } from './types'
export type { HeaderMenuItemsType } from './types'
export type { FooterMenuItemsType } from './types'
export type { ItemsSliderType } from './types'
export type { FlexWrapperType } from './types'
